### ISSUE TITLE
Repeater value count

### ISSUE THREAD

**Issue by Almamun444** [cristian-ungureanu/customizer-repeater#15]
Hi, i am using customizer-repeater as well as and grateful to all of you guys, 
but i can't count repeater value to set slider activation.
I appropriate if you guys let me know about that,
Another problem was faced repeater within repeater not working, when i am going to create social link for team section or others.
Thanks a lot.
Regards from Mamun.

**Comment by cristian-ungureanu** [comment]
Hey @Almamun444, have you checked the last update? I've made an update yesterday. The social repeater should work. I don't understand what you want to count, give more details please.

**Comment by Almamun444** [comment]
Thanks for your reply. 
I had made a team section with repeater, but social icon i can't repeat within repeater,
and need to count the number for repeater.
Thanks for your update, i am going to download again and try.
![test just another wordpress site](https://user-images.githubusercontent.com/13565842/31853457-5a2737ca-b6aa-11e7-817c-cdc468193c4f.png)

**Comment by Almamun444** [comment]
I always get an error, when i wrote like this code
    <?php
               $social_repeaters = json_decode($repeater_item->social_repeater);
                 foreach($social_repeaters as $social_repeater){
                          echo $social_repeater->link;
                  }
       ?>
Please advice me to solve that problem, hope to i can release that project soon.
Thanks again.
![switch just another wordpress site](https://user-images.githubusercontent.com/13565842/31853566-76689288-b6ac-11e7-93c0-9314fd361b31.png)

**Comment by cristian-ungureanu** [comment]
You should do json decode first. See the code in description.

 /*Social repeater is also a repeater so we need to decode it*/
          $social_repeater = json_decode($repeater_item->social_repeater);
          foreach($social_repeater as $social_repeater){
               echo $social_repeater->link;
               echo $social_repeater->icon;
          }

**Comment by Almamun444** [comment]
Hi, 
Do you have way to set up default value for repeater.
if i put like look like
  ****     $wp_customize->add_setting( 'slider_repeater', 
        array(
           'sanitize_callback' => 'customizer_repeater_sanitize',
               'default' => json_encode( array(
          
                  array(
                      "image_url" => get_template_directory_uri().'/dist/images/slider-1.jpg' ,
                      'label'     => esc_html__('Slider Image', ''),
                      "link"      => "#", 
                      "id"        => "slider_image" 
                    ), 

                  array(
                      "repeater_text"  => 'Get Started' ,
                      'label' => esc_html__('Slider Button', ''),
                      "link"  => "#", 
                      "id"    => "slider_btn" 
                    ),  **** 
is not working well, just get only image not any text filed.
I am grateful to you, if you let me know about that.
Thanks

**Comment by cristian-ungureanu** [comment]
`'default' => json_encode( array(

              array(
                  "image_url" => get_template_directory_uri().'/dist/images/slider-1.jpg' ,
                  'label'     => esc_html__('Slider Image', ''), <= this doesn't exist
                  "link"      => "#", 
                  "id"        => "slider_image" <= you can get rid of this
                ), 

              array(
                  "repeater_text"  => 'Get Started' , <= this doesn't exist
                  'label' => esc_html__('Slider Button', ''), <= this doesn't exist
                  "link"  => "#", 
                  "id"    => "slider_btn" <= you can get rid of this
                ),`

You can only use those values:
icon_value, text, text2, link, link2, image_url, choice, title, subtitle, shortcode, color, color2

Here's an example:

`'default' => json_encode(  

		array(  
			array(  
				'image_url' => get_template_directory_uri().'/dist/images/slider-1.jpg' ,
				'title'     => esc_html__( 'Happy Customer', 'parallax-one' ),
				'subtitle'  => esc_html__( 'Lorem ipsum', 'parallax-one' ),
				'text'      => esc_html__( 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel eros sit amet arcu vestibulum accumsan in in leo. Fusce malesuada vulputate faucibus. Integer in hendrerit nisi. Praesent a hendrerit urna. In non imperdiet elit, sed molestie odio. Fusce ac metus non purus sollicitudin laoreet.', 'parallax-one' ),
				'id'        => 'parallax_one_56fd526edcd4e',
			),
			array(
				'image_url' => get_template_directory_uri().'/dist/images/slider-1.jpg' ,
				'title'     => esc_html__( 'Happy Customer', 'parallax-one' ),
				'subtitle'  => esc_html__( 'Lorem ipsum', 'parallax-one' ),
				'text'      => esc_html__( 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel eros sit amet arcu vestibulum accumsan in in leo. Fusce malesuada vulputate faucibus. Integer in hendrerit nisi. Praesent a hendrerit urna. In non imperdiet elit, sed molestie odio. Fusce ac metus non purus sollicitudin laoreet.', 'parallax-one' ),
			),
			array(
				'image_url' => get_template_directory_uri().'/dist/images/slider-1.jpg' ,
				'title'     => esc_html__( 'Happy Customer', 'parallax-one' ),
				'subtitle'  => esc_html__( 'Lorem ipsum', 'parallax-one' ),
				'text'      => esc_html__( 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel eros sit amet arcu vestibulum accumsan in in leo. Fusce malesuada vulputate faucibus. Integer in hendrerit nisi. Praesent a hendrerit urna. In non imperdiet elit, sed molestie odio. Fusce ac metus non purus sollicitudin laoreet.', 'parallax-one' ),
			),
		)
	);`
